/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Profile = IDL.Record({
  'dob' : IDL.Text,
  'pan' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'pincode' : IDL.Text,
});
export const LoanApplication = IDL.Record({
  'status' : IDL.Text,
  'trackingNumber' : IDL.Nat,
  'loanOfferId' : IDL.Nat,
  'profile' : Profile,
});
export const LoanOffer = IDL.Record({
  'id' : IDL.Nat,
  'loanDurationMonths' : IDL.Nat,
  'loanAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'interestRate' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllLoanApplications' : IDL.Func(
      [],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'getApplicationStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getLoanApplication' : IDL.Func([IDL.Nat], [LoanApplication], ['query']),
  'getLoanOffers' : IDL.Func([], [IDL.Vec(LoanOffer)], ['query']),
  'submitLoanApplication' : IDL.Func([Profile, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Profile = IDL.Record({
    'dob' : IDL.Text,
    'pan' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const LoanApplication = IDL.Record({
    'status' : IDL.Text,
    'trackingNumber' : IDL.Nat,
    'loanOfferId' : IDL.Nat,
    'profile' : Profile,
  });
  const LoanOffer = IDL.Record({
    'id' : IDL.Nat,
    'loanDurationMonths' : IDL.Nat,
    'loanAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'interestRate' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllLoanApplications' : IDL.Func(
        [],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'getApplicationStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getLoanApplication' : IDL.Func([IDL.Nat], [LoanApplication], ['query']),
    'getLoanOffers' : IDL.Func([], [IDL.Vec(LoanOffer)], ['query']),
    'submitLoanApplication' : IDL.Func([Profile, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };