/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GoldRates {
  'city' : string,
  'rate22K' : bigint,
  'rate24K' : bigint,
  'rate18K' : bigint,
  'lastUpdated' : bigint,
  'isLive' : boolean,
}
export interface LoanApplication {
  'status' : string,
  'trackingNumber' : bigint,
  'loanOfferId' : bigint,
  'profile' : Profile,
}
export interface LoanOffer {
  'id' : bigint,
  'loanDurationMonths' : bigint,
  'loanAmount' : bigint,
  'name' : string,
  'description' : string,
  'interestRate' : number,
}
export interface Profile {
  'dob' : string,
  'pan' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'mobile' : string,
  'pincode' : string,
}
export interface _SERVICE {
  'getAllLoanApplications' : ActorMethod<[], Array<LoanApplication>>,
  'getApplicationStatus' : ActorMethod<[bigint], string>,
  'getGoldRates' : ActorMethod<[string], GoldRates>,
  'getLoanApplication' : ActorMethod<[bigint], LoanApplication>,
  'getLoanOffers' : ActorMethod<[], Array<LoanOffer>>,
  'submitLoanApplication' : ActorMethod<[Profile, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
